### ISSUE TITLE
Error in terminal efter every messgage

### ISSUE THREAD

**Issue by 5731la** [Jan200101/Appu-cogs#3]
After I start the terminal every time I type in anything in discord it prints a error:
```
Ignoring exception in message
Traceback (most recent call last):
  File "/home/gido5731/.local/lib/python3.5/site-packages/discord/client.py", line 223, in _run_event
    yield from coro(*args, **kwargs)
  File "/home/gido5731/Discord-Selfbot/cogs/terminal.py", line 242, in on_message
    if (message.channel.id in self.sessions and self.enabled and message.author.id == message.server.me.id): # DO NOT DELETE
AttributeError: 'Message' object has no attribute 'server'
```
The command wont work and nothing is executed.

**Comment by appu1232** [comment]
This cog is outdated. It has only been partially updated for rewrite. For now it's not supported.

**Comment by 5731la** [comment]
Damn, that sucks, is there another way to execute commands through the bot?

**Comment by appu1232** [comment]
Hm, I haven't looked at this in a while and would need to confirm with a more thorough look-through, but from what I can see, it might be enough to just change every instance of the world `server` in the file to `guild` (same with `servers` to `guilds`). See if that works. If it does, then great. If not, then you're out of options.

**Comment by 5731la** [comment]
That worked, Ill make a pull request ASAP
